welcome_text = (
    "👋 Assalomu alaykum!\n\n"
    "🤖 Men Professional File Converter Bot'man!\n\n"
    "📋 Men quyidagi konvertatsiyalarni amalga oshiraman:\n\n"
    "📥 <b>TO PDF:</b>\n"
    "• 🖼 JPG → PDF\n"
    "• 📝 WORD → PDF\n"
    "• 📊 POWERPOINT → PDF\n"
    "• 📈 EXCEL → PDF\n"
    "• 🌐 HTML → PDF\n\n"
    "📤 <b>FROM PDF:</b>\n"
    "• 📷 PDF → JPG\n"
    "• 📝 PDF → WORD\n"
    "• 📊 PDF → POWERPOINT\n"
    "• 📈 PDF → EXCEL\n"
    "• 📋 PDF → PDF/A\n\n"
    "❗️ <b>Muhim:</b> 5 marta konvertatsiyadan keyin "
    "2 ta do'stingizni taklif qilishingiz kerak!\n\n"
    "Konvertatsiya turini tanlang 👇"
)